default: &default
  adapter: postgresql
  encoding: utf8
  host: <%=ENV.fetch("DB_HOST", "localhost") %>
  username: <%=ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%=ENV.fetch("DB_PASSWORD", "postgres")%>

development:
  <<: *default
  database: development
  pool: 5

test:
  <<: *default
  database: test
  pool: 5

production:
  <<: *default
  database: production
  pool: 60
